# Railway Configuration
# This file tells Railway how to deploy your app

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.backend"



[environments.production]
ALLOWED_ORIGINS = "*"
ENVIRONMENT = "production"
