# Railway Configuration
# This file tells Railway how to deploy your app

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.backend"



[environments.production]
ALLOWED_ORIGINS = "https://potato-disease.vercel.app,https://potato-disease-frontend.vercel.app"
ENVIRONMENT = "production"
